# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-devops-exercise-docker'
  imageRepository: 'jeremiedevops/devops_exercise'
  containerRegistry: 'JeremieHub'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: './my-app/pom.xml'    
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    goals: 'package'

- task: CmdLine@2
  inputs:
    script: |      
      pwd
      ls -l   
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    containerRegistry: $(containerRegistry)
    repository: $(imageRepository)
    command: 'buildAndPush'
    Dockerfile: 'DockerFile'
    tags: |
          $(Build.BuildId)
- task: CmdLine@2
  inputs:
    script: |
      sudo docker ps -a
      sudo docker images
      sudo docker run --name  "test_$(Build.BuildId)" devopsworkking/devops_exercise:$(Build.BuildId)